config/routes.rb
Rails.application.routes.draw do
  scope module: :public do
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  scope module: :public do
    resources :orders, only: [:show, :new, :index, :create]
    post 'confirm' => 'orders#confirm'
    get 'confirm' => 'orders#confirm'
    get 'complete' => 'orders#complete'
  end

  scope module: :public do
    delete 'cart_items' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]
  end

  scope module: :public do
    get 'my_page' => 'customers#show'
    get 'information/edit' => 'customers#edit'
    patch 'information/edit' => 'customers#update'
    get 'unsubscribe' => 'customers#unsubscribe'
    patch 'withdrawal' => 'customers#withdrawal'

  end

  scope module: :public do
    resources :items, only: [:show, :index]
  end

  scope module: :public do
    root to:"homes#top"
    get 'about' => 'homes#about', as: 'about'
  end



  #order_detailもありわかりません質問
  namespace :admin do
    resources :order_details, only: [:update]
  end

  namespace :admin do
    resources :orders, only: [:show, :update]
  end

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
  end

  namespace :admin do
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
  end

  namespace :admin do
    root to: 'homes#top'
  end



  # 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def display_address
    "〒" + postal_code + " " + address + " " + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car_item.rb
class CarItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy

  has_many :orders, dependent: :destroy

  has_many :addresses, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :order_details, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  has_one_attached :profile_image

  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/cake_sample.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }

  enum status: { waiting_deposit: 0, payment_confirmation: 1, in_production: 2, preparing_to_ship: 3, sent: 4}


end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: { not_making: 0, waiting_making: 1, making: 2, making_end: 3 }
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers=Customer.all
  end

  def show
    @customer=Customer.find(params[:id])
  end

  def edit
    @customer=Customer.find(params[:id])
  end

  def update
    customer = Customer.find(params[:id])
    customer.update(customer_params)
    redirect_to edit_admin_customer_path(customer)
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_deleted)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders=Order.all
    
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items=Item.all
  end

  def new
    @item=Item.new
  end

  def create
    item = Item.new(post_image_params)
    item.save
    redirect_to admin_item_path(item)
  end

  def show
    @item=Item.find(params[:id])
  end

  def edit
    @item=Item.find(params[:id])
  end

  def update
    item =Item.find(params[:id])
    item.update(post_image_params)
    redirect_to admin_items_path
  end

  private

  def post_image_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :profile_image)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order=Order.find(params[:id])
    @order_details=@order.order_details
    @total_price=0

  end

  def update
    #binding.pry
    @order=Order.find(params[:id])
    @order_details = OrderDetail.where(order_id: params[:id])
    if @order.update(order_params)
      @order_details.update_all(making_status: 1) if @order.status == "payment_confirmation"
       ## ①注文ステータスが「入金確認」とき、製作ステータスを全て「製作待ち」に更新する
    end
    redirect_to admin_order_path(@order)
    #binding.pry
  end
end




private
  def order_params
    params.require(:order).permit(:payment_method, :postal_code, :address, :name, :customer_id, :shipping_cost, :total_payment, :status)
  end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/customers/edit.html.erb
<main>
  <%= form_with model: @customer,url: admin_customer_path(@customer),method: :patch do |f| %>

    <h2 class="mb-4"><%= @customer.last_name + @customer.first_name %>さんの会員情報編集</h2>

    <dl class="row">
    <dt class="col-2"><p>氏名</p></dt>
    <dd class="col-10"><%= f.text_field :last_name %> <%= f.text_field :first_name %></dd>

    <dt class="col-2"><p>フリガナ</p></dt>
    <dd class="col-10"><%= f.text_field :last_name_kana %> <%= f.text_field :first_name_kana %></dd>

    <dt class="col-2"><p>郵便番号</p></dt>
    <dd class="col-10"><%= f.text_field :postal_code %></dd>

    <dt class="col-2"><p>住所</p></dt>
    <dd class="col-10"><%= f.text_field :address %></dd>

    <dt class="col-2"><p>電話番号</p></dt>
    <dd class="col-10"><%= f.text_field :telephone_number %></dd>

    <dt class="col-2"><p>メールアドレス</p></dt>
    <dd class="col-10"><%= f.text_field :email %></dd>

  </dl>

  <p>会員ステータス</p>
  <p><%= f.radio_button :is_deleted, false %>有効</p>
  <p><%= f.radio_button :is_deleted, true %>退会</p>
  <%= f.submit '編集内容を保存',class: "btn btn-success" %>

  <% end %>


</main>

app/views/admin/customers/index.html.erb
<main>
  <h2 class="mb-4">会員一覧</h2>


  <div class="d-flex justify-content-between w-100">
    <table class="table w-60">
      <thead>
        <th>会員ID</th>
        <th>氏名</th>
        <th>メールアドレス</th>
        <th>ステータス</th>
      </thead>
      <tbody>
        <% @customers.each do |customer| %>
        <tr>
          <th><%=customer.id %></th>

          <th>
            <%= link_to admin_customer_path(customer) do %>
            <%=customer.last_name+customer.first_name %>
            <% end %>
          </th>

          <th><%=customer.email %></th>

          <th>
            <% if customer.is_deleted == false %>
             <p class="text-success">有効</p>
            <% else customer.is_deleted == true %>
             <p class="text-secondary">退会</p>
            <% end %>
          </th>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>

</main>

app/views/admin/customers/show.html.erb
<main>
  <h2 class="mb-4"><%= @customer.last_name + @customer.first_name %>さんの会員詳細</h2>


  <dl class="row">
    <dt class="col-2"><p>会員ID</p></dt>
    <dd class="col-10"><%= @customer.id %></dd>

    <dt class="col-2"><p>氏名</p></dt>
    <dd class="col-10"><%= @customer.last_name + " " + @customer.first_name %></dd>

    <dt class="col-2"><p>フリガナ</p></dt>
    <dd class="col-10"><%= @customer.last_name_kana + " " + @customer.first_name_kana %></dd>

    <dt class="col-2"><p>郵便番号</p></dt>
    <dd class="col-10"><%= @customer.postal_code %></dd>

    <dt class="col-2"><p>住所</p></dt>
    <dd class="col-10"><%= @customer.address %></dd>

    <dt class="col-2"><p>電話番号</p></dt>
    <dd class="col-10"><%= @customer.telephone_number %></dd>

    <dt class="col-2"><p>メールアドレス</p></dt>
    <dd class="col-10"><%= @customer.email %></dd>

    <dt class="col-2"><p>会員ステータス</p></dt>
    <dd class="col-10">
      <% if @customer.is_deleted == false %>
        有効
      <% else @customer.is_deleted == true %>
        退会
      <% end %>
    </dd>
  </dl>


  <div><%= link_to "編集する", edit_admin_customer_path(@customer),class: "btn btn-success mb-4" %></div>

  <div><%= link_to "注文履歴一覧を見る", admin_root_path,class: "btn btn-primary" %></div>


</main>