config/routes.rb
Rails.application.routes.draw do
  scope module: :public do
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  scope module: :public do
    resources :orders, only: [:show, :new, :index, :create]
    post 'confirm' => 'orders#confirm'
    get 'confirm' => 'orders#confirm'
    get 'complete' => 'orders#complete'
  end

  scope module: :public do
    delete 'cart_items' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]
  end

  scope module: :public do
    get 'my_page' => 'customers#show'
    get 'information/edit' => 'customers#edit'
    patch 'information/edit' => 'customers#update'
    get 'unsubscribe' => 'customers#unsubscribe'
    patch 'withdrawal' => 'customers#withdrawal'

  end

  scope module: :public do
    resources :items, only: [:show, :index]
  end

  scope module: :public do
    root to:"homes#top"
    get 'about' => 'homes#about', as: 'about'
  end



  #order_detailもありわかりません質問
  namespace :admin do
    resources :order_details, only: [:update]
  end

  namespace :admin do
    resources :orders, only: [:show, :update]
  end

  namespace :admin do
    resources :customers, only: [:index, :show, :edit, :update]
  end

  namespace :admin do
    resources :items, only: [:new, :create, :index, :show, :edit, :update]
  end

  namespace :admin do
    root to: 'homes#top'
  end



  # 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def display_address
    "〒" + postal_code + " " + address + " " + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car_item.rb
class CarItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy

  has_many :orders, dependent: :destroy

  has_many :addresses, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :order_details, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  has_one_attached :profile_image

  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/cake_sample.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }

  enum status: { waiting_deposit: 0, payment_confirmation: 1, in_production: 2, preparing_to_ship: 3, sent: 4}


end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum making_status: { not_making: 0, waiting_making: 1, making: 2, making_end: 3 }
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders=Order.all
    
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items=Item.all
  end

  def new
    @item=Item.new
  end

  def create
    item = Item.new(post_image_params)
    item.save
    redirect_to admin_item_path(item)
  end

  def show
    @item=Item.find(params[:id])
  end

  def edit
    @item=Item.find(params[:id])
  end

  def update
    item =Item.find(params[:id])
    item.update(post_image_params)
    redirect_to admin_items_path
  end

  private

  def post_image_params
    params.require(:item).permit(:name, :introduction, :price, :is_active, :profile_image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header class="mb-4">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark text-dark py-3">
          <div class="container">
            <a class="navbar-brand" href="/">LOGO</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav ml-auto">
                <% if admin_signed_in? %>
                  <li class="nav-item">
                    <%= link_to admin_items_path, class: 'nav-link text-light' do %>
                    商品一覧
                    <% end %>
                  </li>
                  <li class="nav-item">
                    <%= link_to admin_customers_path, class: 'nav-link text-light' do %>
                    会員一覧
                    <% end %>
                  </li>
                  <li class="nav-item">
                    <%= link_to admin_root_path, class: 'nav-link text-light' do %>
                    注文履歴一覧
                    <% end %>
                  </li>
                  <li class="nav-item">
                    <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-light' do %>
                    ログアウト
                    <% end %>
                  </li>
                <% elsif customer_signed_in? %>
                  <li class="nav-item">
                    <%= link_to my_page_path(current_customer), class: 'nav-link text-light' do %>
                    マイページ
                    <% end %>
                  </li>
                  <li class="nav-item">
                    <%= link_to items_path, class: 'nav-link text-light' do %>
                    商品一覧
                    <% end %>
                  </li>
                  <li class="nav-item">
                    <%= link_to cart_items_path, class: 'nav-link text-light' do %>
                    カート
                    <% end %>
                  </li>
                  <li class="nav-item">
                    <%= link_to destroy_customer_session_path, method: :delete, class: 'nav-link text-light' do %>
                    ログアウト
                    <% end %>
                  </li>
                <% else %>
                  <li class="nav-item">
                    <%= link_to about_path, class: 'nav-link text-light' do %>
                    About
                    <% end %>
                  </li>
                  <li class="nav-item">
                    <%= link_to root_path, class: 'nav-link text-light' do %>
                    商品一覧
                    <% end %>
                  </li>
                  <li class="nav-item">
                    <%= link_to new_customer_registration_path, class: 'nav-link text-light' do %>
                    新規登録
                    <% end %>
                  </li>
                  <li class="nav-item">
                    <%= link_to new_customer_session_path, class: 'nav-link text-light' do %>
                    ログイン
                    <% end %>
                  </li>
                <% end %>
    </header>

    <main>
      <div class="container">
        <%= yield %>
      </div>
    </main>

    <footer>
      <div class="container mt-5 ">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>